"""empty message

Revision ID: ffc266a64c40
Revises: 
Create Date: 2020-10-17 22:51:34.166350

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ffc266a64c40'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('video',
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('frame', sa.Integer(), nullable=False),
    sa.Column('millisec', sa.Integer(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('gender', sa.String(length=10), nullable=False),
    sa.Column('img_person', sa.String(length=100), nullable=False),
    sa.Column('top_color', sa.Integer(), nullable=False),
    sa.Column('bottom_color', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('uid')
    )
    op.drop_table('testtwo')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('testtwo',
    sa.Column('id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('frame', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('millisec', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('age', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('gender', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('img_person', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('top_color', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('bottom_color', mysql.INTEGER(), autoincrement=False, nullable=True),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('video')
    # ### end Alembic commands ###
